gamma = 0.99  # discount rate
lambda_ = 0.95  # GAE parameter
epsilon = 0.2  # clip epsilon
v_epsilon = 1  # value clip epsilon
actor_N = 4  # Actor number > 1
frames_M = int(2e5)  # Total frames
step_T = 512  # move steps
epochs = 5  # train epochs
batch_size = 32
coef_value = 1  # coef of value loss
coef_entropy = 0.01  # coef of entropy regular
flag_ad_normal = True  # Whether normalize advantage value
flag_clip_value = False  # Whether clip the ad value
max_clip_norm = 0.5  # clip_by_global_norm(clip_norm)
EPS = 1e-8