gamma = 0.99  # discount rate
lambda_ = 0.95  # GAE parameter
epsilon = 0.1  # clip epsilon
v_epsilon = 1  # value clip epsilon
actor_N = 8  # Actor number > 1
# frames_M = int(5e6)  # Total frames
frames_M = int(1e7)  # Total frames
step_T = 128  # move steps
data_size = actor_N * step_T  # each update datasize
iter_nums = (frames_M - 1) // data_size + 1  # total iters
epochs = 4  # train epochs
# batch_size = 64
batch_size = 256
coef_value = 0.5  # coef of value loss, fix loss nan
coef_entropy = 0.01  # coef of entropy regular
flag_ad_normal = True  # Whether normalize advantage value
flag_clip_value = False  # Whether clip the ad value
init_lr = 2.5e-4  # init learning rate
flag_anneal_lr = True  # anneal learning rate
EPS = 1e-8