gamma = 0.99  # discount rate
lambda_ = 0.95  # GAE parameter
epsilon = 0.2  # clip epsilon
v_epsilon = 1  # value clip epsilon
actor_N = 4  # Actor number > 1
frames_M = int(2e5)  # Total frames
step_T = 512  # move steps
data_size = actor_N * step_T  # each update datasize
iter_nums = (frames_M - 1) // data_size + 1  # total iters
epochs = 5  # train epochs
batch_size = 32
coef_value = 1  # coef of value loss
coef_entropy = 0.01  # coef of entropy regular
flag_ad_normal = True  # Whether normalize advantage value
flag_clip_value = False  # Whether clip the ad value
init_lr = 3e-4  # init learning rate
flag_anneal_lr = True  # anneal learning rate
EPS = 1e-8