gamma = 0.99  # discount rate
coef_gae = 0.95  # GAE parameter
epsilon = 0.1  # clip epsilon
v_epsilon = 1  # value clip epsilon
num_envs = 4  # Actor number > 1
num_steps = 512  # move steps
total_timesteps = int(5e5)  # Total frames
epochs = 4  # train epochs
# batch_size = 32
batch_size = 32
coef_value = 1  # coef of value loss
coef_entropy = 0.01  # coef of entropy regular
flag_ad_normal = True  # Whether normalize advantage value
flag_clip_value = False  # Whether clip the ad value
learning_rate = 2.5e-4  # init learning rate
flag_anneal_lr = True  # anneal learning rate
max_grad_clip_norm = 0.5
EPS = 1e-8