gamma = 0.99  # discount rate
lambda_ = 0.95  # GAE parameter
epsilon = 0.1  # clip epsilon
v_epsilon = 1  # value clip epsilon
num_envs = 8  # Actor number > 1
total_timesteps = int(1e7)  # Total frames
num_steps = 128  # move steps
epochs = 4  # train epochs
# batch_size = 64
batch_size = 256
coef_value = 0.5  # coef of value loss, fix loss nan
coef_entropy = 0.01  # coef of entropy regular
flag_ad_normal = True  # Whether normalize advantage value
flag_clip_value = False  # Whether clip the ad value
init_lr = 2.5e-4  # init learning rate
flag_anneal_lr = True  # anneal learning rate
EPS = 1e-8